# fly.toml app configuration file generated for webrtc-mern on 2023-07-24T12:49:18+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "webrtc-mern"
primary_region = "nrt"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
[env]
  PORT = 8000
  CLIENT_ENDPOINT = "https://webrtc-mern.vercel.app"
